### PR TITLE
Use System.Buffers.Text.Base64 for Utf8

### PR DESCRIPTION
**Pull request by Tornhoof**
Use existing, optimized B64 Code for UTF8.
@Reris That's using the types from your comment.

### CODE REVIEW

**Comment by Reris** [comment]
ok. give me a moment for testing. 1 issue i've found in 3.3.0 is "" deserializes to null instead of empty

**Comment by Reris** [comment]
```

    [Theory]
    [InlineData(true, 10, @"{""bytes"":""AAECAwQFBgcICQ=="",""id"":42}")]
    [InlineData(true, 0, @"{""bytes"":"""",""id"":42}")]
    [InlineData(true, null, @"{""id"":42}")]
    [InlineData(false, 10, @"{""bytes"":""AAECAwQFBgcICQ=="",""id"":42}")]
    [InlineData(false, 0, @"{""bytes"":"""",""id"":42}")]
    [InlineData(false, null, @"{""id"":42}")]
    public void Serialize_ByteArray_ShouldUseBase64(bool utf8, int? arraySize, string expected)
    {
        // Arrange
        var bytes = arraySize.HasValue ? Enumerable.Range(0, arraySize.Value).Select(b => (byte)b).ToArray() : null;
        var data = new SimpleData { Id = 42, Bytes = bytes };

        // Act
        var result = utf8 ? Encoding.UTF8.GetString(JsonSerializer.SerializeBytes(data)) : JsonSerializer.SerializeString(data);

        // Assert
        result.Should().Be(expected);
    }

    [Theory]
    [InlineData(true, 10, @"{""bytes"":""AAECAwQFBgcICQ=="",""id"":42}")]
    [InlineData(true, 0, @"{""bytes"":"""",""id"":42}")]
    [InlineData(true, null, @"{""id"":42}")]
    [InlineData(false, 10, @"{""bytes"":""AAECAwQFBgcICQ=="",""id"":42}")]
    [InlineData(false, 0, @"{""bytes"":"""",""id"":42}")]
    [InlineData(false, null, @"{""id"":42}")]
    public void Deserialize_ByteArray_ShouldUseBase64(bool utf8, int? arraySize, string value)
    {
        // Arrange
        var bytes = arraySize.HasValue ? Enumerable.Range(0, arraySize.Value).Select(b => (byte)b).ToArray() : null;
        var expected = new SimpleData { Id = 42, Bytes = bytes };

        // Act
        var result = utf8
                         ? (SimpleData)JsonSerializer.Deserialize(typeof(SimpleData), Encoding.UTF8.GetBytes(value))!
                         : JsonSerializer.Deserialize<SimpleData>(value);

        // Assert
        result.Should().BeEquivalentTo(expected);
    }


    public class SimpleData
    {
        public int Id { get; set; }
        public byte[]? Bytes { get; set; } = default!;
    }
```

**Comment by Tornhoof** [comment]
Ah thanks, I fixed that and included your test cases.

**Comment by Reris** [comment]
Ok good and even faster than my version. :)
Just 2 little things:
`SpanJsonOptions.ByteArrayOptions` -> rename to `SpanJsonOptions.ByteArrayOption` to solve a potential naming conflict.

And a little wish: It would be great if `ResolverBase<TSymbol, TResolver>.ResolverBase.BuildFormatter` could be made `protected virtual` to allow more advanced customizations like that.

**Pull request merged**
