### PR TITLE
count utf8 bytes

### PR DESCRIPTION
**Pull request by dv00d00**

### CODE REVIEW

**Comment by dv00d00** [comment]
Does it deserve an extra test case?

**Comment by Tornhoof** [comment]
Ah you were faster than me :)
I'll merge your branch and merge my tests against it, the actual change is the same in both PRs.

**Comment by dv00d00** [comment]
dont waste your time on it :D

**Comment by Tornhoof** [comment]
Ah small correction, using ByteCount is slightly more correct but way more inefficient as it does a pretty much a full utf8 encoding for it. 
Using MaxByteCount is less correct, but simply does a fixed multiplication.
So I'll use MaxByteCount.

**Pull request merged**
