### PR TITLE
Loose nesting limit.

### PR DESCRIPTION
**Pull request by hez2010**

### CODE REVIEW

**Comment by Tornhoof** [comment]
Why do you think that works in all cases?

**Comment by hez2010** [comment]
@Tornhoof 
I don't think it will work in all cases, but the previous 256 nesting limit often failed while process long string. So I just loose the limit to make it useable in wider cases.

**Comment by Tornhoof** [comment]
I'm not sure what data structure you're serializing which requires a nesting of more 256 levels, this is to prevent StackOverflows in Serialization, so that limit can't be easily increased to such unsafe levels.
If you really need such levels, i.e. for highly nested tree structures, and your system can handle it, then you could implement an ICustomJsonFormatter for that type and call once/multiple times ``jsonWriter.DecrementDepth`` yourself prior to calling the normal CustomFormatter for the type.
Specifically if you have a classic tree with only one Node type this should work.

**Comment by hez2010** [comment]
Confirmed that the stackoverflow previously I experienced was caused by a bug from an old version of SpanJson, and in the latest version the bug has been fixed.

Closed.

**Pull request closed without merging**
